# Generated by Django 3.2.9 on 2021-11-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=3, upload_to='category/'),
            preserve_default=False,
        ),
    ]
