# Generated by Django 3.2.9 on 2021-11-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='adv',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='краткое описание'),
        ),
    ]
