# Generated by Django 3.2.9 on 2021-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'קטרגוריות'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name': 'Subcategory', 'verbose_name_plural': 'תת קטגוריות'},
        ),
        migrations.AlterField(
            model_name='product',
            name='adv',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='תיאור לקידום'),
        ),
    ]
