# Generated by Django 3.2.9 on 2021-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_adv', models.CharField(blank=True, max_length=500, null=True, verbose_name='תיאור לקידום')),
                ('catalog_adv', models.CharField(blank=True, max_length=500, null=True, verbose_name='תיאור לקידום')),
                ('about_adv', models.CharField(blank=True, max_length=500, null=True, verbose_name='תיאור לקידום')),
                ('contact_adv', models.CharField(blank=True, max_length=500, null=True, verbose_name='תיאור לקידום')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='adv',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='תיאור לקידום'),
        ),
    ]
