# Generated by Django 3.2.9 on 2021-11-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211127_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='main_adv',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='main_adv'),
        ),
    ]
