# Generated by Django 3.2.10 on 2021-12-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_adv_main_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='main_adv',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='main_adv'),
        ),
    ]
