# Generated by Django 3.2.10 on 2022-01-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_adv_main_adv'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
