# Generated by Django 3.2.9 on 2021-12-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transport_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
    ]
