# Generated by Django 3.2.9 on 2021-11-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d')),
                ('chort_entry', models.CharField(max_length=150, verbose_name='краткое описание ')),
                ('name_entry_1', models.CharField(db_index=True, max_length=400)),
                ('big_word', models.CharField(blank=True, max_length=1, null=True)),
                ('entry_1', models.TextField(verbose_name='полное описание')),
                ('entry_in_block', models.TextField(verbose_name='полное описание')),
                ('name_entry_2', models.CharField(blank=True, db_index=True, max_length=400, null=True)),
                ('entry_2', models.TextField(blank=True, null=True, verbose_name='полное описание')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=50, null=True)),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True, verbose_name='for seo')),
            ],
        ),
    ]
