# Generated by Django 3.2.9 on 2021-11-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='entry_in_block',
            field=models.TextField(blank=True, null=True, verbose_name='текст в блоке'),
        ),
    ]
