# Generated by Django 3.2.9 on 2021-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_content_entry_in_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='big_word',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='большая буква которая относится к первому тексту'),
        ),
        migrations.AlterField(
            model_name='content',
            name='chort_entry',
            field=models.TextField(max_length=150, verbose_name='краткое описание '),
        ),
        migrations.AlterField(
            model_name='content',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='entry_1',
            field=models.TextField(blank=True, null=True, verbose_name='полное описание 1'),
        ),
        migrations.AlterField(
            model_name='content',
            name='entry_2',
            field=models.TextField(blank=True, null=True, verbose_name='полное описание 2'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d', verbose_name='1 картинка ( на главной и на главной блога )'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d', verbose_name=' 2 картинка, ( не обязательно )'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name_entry_1',
            field=models.CharField(db_index=True, max_length=400, verbose_name='название текста 1'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name_entry_2',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True, verbose_name='название текста 2'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='слаг'),
        ),
    ]
