# Generated by Django 3.2.9 on 2021-12-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211208_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
