# Generated by Django 3.2.9 on 2021-12-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_content_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='big_word',
        ),
        migrations.AlterField(
            model_name='content',
            name='name_entry_1',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True, verbose_name='название текста 1'),
        ),
    ]
